# This configuration file is used for Scout APM.
# Environment variables can also be used to configure Scout. See our help docs at https://docs.scoutapm.com#environment-variables for more information.
common: &defaults

  # key: Your Organization key for Scout APM. Found on the settings screen.
  # - Default: none
  key: OMtoV1IxudGCAOHKuncb

  # log_level: Verboseness of logs.
  # - Default: 'info'
  # - Valid Options: debug, info, warn, error
  # log_level: debug

  # name: Application name in APM Web UI
  # - Default: the application names comes from the Rails or Sinatra class name
  # name:

  # monitor: Enable Scout APM or not
  # - Default: none
  # - Valid Options: true, false
  monitor: true

production:
  <<: *defaults
  name: RIMS CROMA
  key: OMtoV1IxudGCAOHKuncb

development:
  <<: *defaults
  monitor: false  
  name: beam_saas_development
  key: JdpLbv01KXCCJJt5oTnp

test:
  <<: *defaults
  monitor: false

staging:
  <<: *defaults
  name: beam_saas_development
  key: JdpLbv01KXCCJJt5oTnp

