module CheckPermission
  extend ActiveSupport::Concern

  included do
    before_action :authenticate_user!, unless: :devise_controller?, :except => ["lot_information", "create_quotation", "download_manifesto"]
    before_action :check_permission, unless: :devise_controller?, :except => ["lot_information", "create_quotation", "download_manifesto", "forward_import_document", "master_skus", "vendor_masters", "distribution_centers", "import_gi_document"]
  end

  def permissions
    {

      superadmin: {  #role as key
        "admin/roles": [:index, :create, :update, :destroy, :show], #controller name as key, actions as values
        "admin/users": [:index, :create, :update, :destroy, :show , :search, :get_username],
        "admin/distribution_centers": [:index, :create, :update, :destroy, :show, :search, :distribution_center_uploads],
        "admin/lookup_keys": [:index, :create, :update, :destroy, :show, :import],
        "admin/lookup_values": [:index, :create, :update, :destroy, :show, :import, :search, :get_lookup_value_parents],
        "admin/clients": [:index, :create, :update, :destroy, :show, :search],
        "admin/attribute_masters": [:index, :create, :update, :destroy, :show, :import],
        "admin/client_attribute_masters": [:index, :create, :update, :destroy, :show, :import],
        "admin/client_category_mappings": [:index, :create, :update, :destroy, :show, :import],
        "admin/client_sku_masters": [:index, :create, :update, :destroy, :show],
        "admin/categories": [:index, :create, :update, :destroy, :show, :import, :get_category_parents],
        "admin/client_categories": [:index, :create, :update, :destroy, :show, :import, :get_client_category_parents, :get_all_client_category],
        "admin/cost_values": [:index, :import],
        "admin/channels": [:index, :create, :update, :destroy, :show],
        "admin/cost_labels": [:index, :create, :update, :destroy, :show],
        "admin/orders": [:index, :create, :update, :destroy, :show, :import],
        "admin/customer_return_reasons": [:index, :create, :update, :destroy, :show, :import],
        "admin/email_templates": [:index, :create, :update, :destroy, :show, :import],
        "admin/reminders": [:index, :create, :update, :destroy, :show, :import],
        "admin/invoices": [:index, :create, :update, :destroy, :show, :import],
        "admin/master_file_uploads": [:index, :create , :fetch_grading_type , :fetch_distribution_centers, :retry_upload],
        "admin/invoice_inventory_details": [:index, :create, :update, :destroy, :show, :import],
        "api/v1/lookups": [:inventory_store_status, :inventory_warehouse_status, :logistics_order_types, :country, :states, :cities, :get_child_values, :get_email_templates, :reminder_status, :get_distribution_center_types, :get_customer_return_reasons, :get_client_sku_masters, :get_client_categories, :get_dealer_types],
        "api/v1/client_categories": [:all_category_data],
        "admin/rules": [:index, :create, :update, :destroy, :show, :import, :import_client],
        "admin/disposition_rules": [:index, :create, :update, :destroy, :show],
        "api/v1/store/returns/customer_returns": [:category_rules, :upload, :generate_rr, :finalize_grading,:finalize_grading,:delete_images],
        "api/v1/categories": [:all_category, :leaf_category, :get_details, :test_rules, :grading_rules, :client_category_grading_rules],
        "api/v1/store/invoices": [:fetch_inventories],
        "admin/logistics_partners": [:index, :create, :update, :destroy, :show],
        "admin/qc_configurations": [:index, :create, :update, :destroy, :show],
        "admin/return_inventory_informations": [:index, :create, :update, :destroy, :show],
        "api/v1/warehouse/return_initiation/return_inventory_informations": [:index, :create, :show, :update, :destroy, :edit, :search_return_items],
        "api/v1/warehouse/return_initiation/return_creation_file_uploads": [:index, :create, :show, :update, :destroy, :edit],
        "api/v1/warehouse/return_initiation/return_creations": [:index, :create, :show, :update, :destroy, :edit, :search_return_items, :create_return_items, :delete_return_items],
        "api/v1/warehouse/return_initiation/return_items": [:index, :create, :show, :update, :destroy, :edit, :search, :delete_return_items, :create_return_items],
        "api/v1/warehouse/return_initiation/return_eligibility_validations": [:index, :create, :show, :update, :destroy, :edit, :approve, :reject, :search],
        "api/v1/warehouse/return_initiation/return_manual_dispositions": [:index, :create, :show, :update, :destroy, :edit, :search, :assign_disposition],
        "admin/alert_configurations": [:index, :create, :update, :destroy, :show, :import],
        "admin/repair_parts": [:index, :create, :update, :destroy, :show, :import],
        "admin/vendor_masters": [:index, :import, :delete_vendor, :uploaded_rate_cards, :export_rate_cards],
        "api/v1/dms/dealers": [:index, :create, :update, :destroy, :show],
        "api/v1/warehouse/users": [:index, :fetch_all_info, :create, :show, :update, :destroy, :restore_user],
        "api/v1/warehouse/alert_inventories": [:index],
        "api/v1/warehouse/manual_processes": [:bucket_movement, :delete_item, :get_dispositions],
        "api/v2/warehouse/saleables": [:index, :show, :item_details, :reserve_items, :un_reserve, :update_payment_details, :get_payment_details, :get_buyers, :create_buyer, :update_disposition, :get_city_and_states, :dispositions, :set_dispositions],
        "api/v2/warehouse/inventory_file_uploads": [:index, :create, :download_competitive_liquidations],
        "api/v2/account_settings": [:show],
        "api/v1/physical_inspections": [:index, :create, :scan_inventories, :update_status, :update_assignees, :brands, :articles, :categories, :dispositions, :assignees, :issue_items, :get_sub_locations],
        "api/v1/issue_inventories": [:index, :update_status, :pending_approvals, :reject, :correct_excess, :approve, :get_filter_locations],
        "api/v1/scan_inventories": [:show],
        "api/v1/transfer_inventories": [:index, :dispositions_type, :dispositions, :dispositions_sub_status, :transfer_inventories],
        "api/v2/warehouse/ecom_liquidations": [:dispatch_orders],
        "api/v2/warehouse/oms/forward/purchase_orders": [:index, :create, :show, :items, :vendors, :inventories_data, :locations, :detail],
        "api/v2/warehouse/order_management_systems": [:index, :create, :show, :items],
        "api/v2/warehouse/oms/reverse/sales_orders": [:index, :create, :show, :items, :vendor_details, :location_details, :article_id_list, :article_description_list, :item_details, :create_invoice, :cancel_order, :print_order],
        "api/v2/warehouse/oms/reverse/back_orders": [:index, :create, :show, :item_details, :move_to_so, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/lease_orders": [:index, :create, :show, :items, :vendor_details, :location_details, :article_id_list, :article_description_list, :item_details, :cancel_order, :print_order],
        "api/v2/warehouse/oms/reverse/transfer_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/repair_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/replacement_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/replacement_customer_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/outward_return_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/forward/purchase_order_receipt_challans": [:index, :create, :details]
      },

      central_admin: {  #role as key
        "admin/roles": [:index, :create, :update, :destroy, :show], #controller name as key, actions as values
        "admin/users": [:index, :create, :update, :destroy, :show , :search, :get_username],
        "admin/distribution_centers": [:index, :create, :update, :destroy, :show, :search, :distribution_center_uploads],
        "admin/lookup_keys": [:index, :create, :update, :destroy, :show, :import],
        "admin/lookup_values": [:index, :create, :update, :destroy, :show, :import, :search, :get_lookup_value_parents],
        "admin/clients": [:index, :create, :update, :destroy, :show, :search],
        "admin/attribute_masters": [:index, :create, :update, :destroy, :show, :import],
        "admin/client_attribute_masters": [:index, :create, :update, :destroy, :show, :import],
        "admin/client_category_mappings": [:index, :create, :update, :destroy, :show, :import],
        "admin/client_sku_masters": [:index, :create, :update, :destroy, :show],
        "admin/categories": [:index, :create, :update, :destroy, :show, :import, :get_category_parents],
        "admin/client_categories": [:index, :create, :update, :destroy, :show, :import, :get_client_category_parents, :get_all_client_category],
        "admin/cost_values": [:index, :import],
        "admin/channels": [:index, :create, :update, :destroy, :show],
        "admin/cost_labels": [:index, :create, :update, :destroy, :show],
        "admin/orders": [:index, :create, :update, :destroy, :show, :import],
        "admin/customer_return_reasons": [:index, :create, :update, :destroy, :show, :import],
        "admin/email_templates": [:index, :create, :update, :destroy, :show, :import],
        "admin/reminders": [:index, :create, :update, :destroy, :show, :import],
        "admin/invoices": [:index, :create, :update, :destroy, :show, :import],
        "admin/master_file_uploads": [:index, :create , :fetch_grading_type , :fetch_distribution_centers, :retry_upload],
        "admin/invoice_inventory_details": [:index, :create, :update, :destroy, :show, :import],
        "api/v1/lookups": [:inventory_store_status, :inventory_warehouse_status, :logistics_order_types, :country, :states, :cities, :get_child_values, :get_email_templates, :reminder_status, :get_distribution_center_types, :get_customer_return_reasons, :get_client_sku_masters, :get_client_categories, :get_dealer_types],
        "api/v1/client_categories": [:all_category_data],
        "admin/rules": [:index, :create, :update, :destroy, :show, :import, :import_client],
        "admin/disposition_rules": [:index, :create, :update, :destroy, :show],
        "api/v1/store/returns/customer_returns": [:category_rules, :upload, :generate_rr, :finalize_grading,:finalize_grading,:delete_images],
        "api/v1/categories": [:all_category, :leaf_category, :get_details, :test_rules, :grading_rules, :client_category_grading_rules],
        "api/v1/store/invoices": [:fetch_inventories],
        "admin/logistics_partners": [:index, :create, :update, :destroy, :show],
        "admin/return_inventory_informations": [:index, :create, :update, :destroy, :show],
        "api/v1/warehouse/return_initiation/return_inventory_informations": [:index, :create, :show, :update, :destroy, :edit, :search_return_items],
        "admin/qc_configurations": [:index, :create, :update, :destroy, :show],
        "admin/alert_configurations": [:index, :create, :update, :destroy, :show, :import],
        "admin/repair_parts": [:index, :create, :update, :destroy, :show, :import],
        "admin/vendor_masters": [:index, :import, :delete_vendor, :uploaded_rate_cards, :export_rate_cards],
        "api/v1/dms/dealers": [:index, :create, :update, :destroy, :show],
        "api/v1/warehouse/users": [:index, :fetch_all_info, :create, :show, :update, :destroy, :restore_user],
        "api/v1/warehouse/alert_inventories": [:index],
        "api/v1/warehouse/gate_passes": [:fetch_gate_passes, :create_consignment_box, :update_box_detail, :complete_consignment, :get_box_conditions, :consignment_box_file_types, :import],
        "api/v1/warehouse/warehouse_grading": [:category_rules, :upload, :generate_rr, :finalize_grading , :warehouse_rules, :delete_images],
        "api/v1/store/returns/customer_returns": [:category_rules, :upload, :generate_rr, :finalize_grading],
        "api/v1/lookups": [:get_customer_return_reasons, :get_warehouse_reasons],
        "api/v1/warehouse/quality_control": [:fetch_inventories, :complete_qc],
        "api/v1/warehouse/stowing": [:fetch_inventories, :set_location, :complete_stowing],
        "api/v1/warehouse/pending_packaging": [:index, :get_inventories, :create_box, :generate_gate_pass, :create_items, :delete_packaging_box],
        "api/v1/warehouse/pick_item": [:index, :get_inventories, :create_items],
        "api/v1/warehouse/liquidations": [:get_vendor_liquidation, :search_vendor, :update_lot_order, :update_liquidation_cell, :fetch_inventories, :generate_csv, :create_lots, :create_manual_dispatch_lot, :dispatch_offline_lot, :regrade_inventories , :moving_lot_creation, :fetch_pending_regrading_inventories, :fetch_beam_inventories, :get_liquidation_requests, :move_to_pending_liquidation, :create_beam_lots, :create_beam_republish_lots, :create_beam_republish_lots_async, :create_contract_lots, :get_liquidation_images, :get_republish_liquidation_images, :get_quotations, :get_email_vendors_list, :update_lot_winner, :get_liquidation_images_page, :remove_excess_items_before_dispatch, :search_item, :get_dispositions, :set_disposition, :get_vendor_contract],
        "api/v2/warehouse/liquidation/channel_allocations": [:index, :mark_e_waste, :category_list, :formatted_category_list, :allocate_channel],
        "api/v2/warehouse/liquidation/price_discovery": [:index, :assign_price],
        "api/v2/warehouse/liquidation/competitive_bidding_price": [:index, :create_lot, :move_to_moq, :buyers, :inventories_images, :calculate_ai_price],
        "api/v2/warehouse/liquidation/contracted_price": [:index, :create_lot, :get_vendor_contract],
        "api/v2/warehouse/liquidation/moq": [:index, :create_lot, :move_to_competative_bidding, :article_id_list, :article_description_list, :liquidation_quantity_based_on_grade, :buyers, :mrp_per_lot],
        "api/v2/warehouse/liquidation/b2c_pending_publish": [:index, :move_to_b2b, :publish, :get_platform_list, :resync_publish],
        "api/v2/warehouse/liquidation_order/b2b/in_progress": [:index, :show, :update, :vendor_list, :reserve, :update_timing, :delete_lots],
        "api/v2/warehouse/liquidation_order/b2b/pending_publish": [:index, :show, :update, :publish, :update_timing, :lot_details, :lot_images, :delete_lots, :remove_lot_items, :index_new],
        "api/v2/warehouse/liquidation_order/b2c/in_progress": [:index, :delete_lots, :update_sales],
        "api/v2/warehouse/liquidation_order/b2c/pending_publish": [:index, :publish],
        "api/v2/warehouse/liquidation_order/pending/decision": [:index, :update, :get_bidders, :republish, :delete_lots],
        "api/v2/warehouse/liquidation_order/pending/b2c_decision": [:index],
        "api/v2/warehouse/liquidation_order/pending/dispatch_confirmation_time": [:index, :update_dispatch_date],
        "api/v2/warehouse/liquidation_order/pending/payment": [:index, :update, :unreserve_sub_lot],
        "api/v2/warehouse/vendor_return/pending_confirmation": [:index, :update_confirmation, :vendor_list, :brand_list],
        "api/v2/warehouse/vendor_return/dispatch": [:index],
        "api/v2/warehouse/liquidation_order/dispatch": [:index],
        "api/v2/warehouse/markdown/pending_price_and_location": [:index, :update_markdowns, :filter_categories, :filter_grade, :get_distribution_center],
        "api/v2/warehouse/markdown/dispatch": [:index],
        "api/v2/warehouse/capital_assets": [:index, :get_distribution_users, :assigned_user, :unassigned_user, :get_dispositions, :set_dispositions],
        "api/v2/dashboard": [:dashboard_embed_url, :ai_discrepancy_reports, :ai_discrepancy_report],
        "api/v2/warehouse/rental/reserve": [:index, :create_rental_reserve, :article_ids_with_quantity, :vendor_master_details, :get_dispositions, :change_disposition],
        "api/v2/warehouse/rental/pending_payment": [:index, :update_status, :unreserve],
        "api/v2/warehouse/rental/out_for_rental": [:index, :update_rental],
        "api/v2/warehouse/callbacks": [:publish, :place_bid, :buy_now, :extend_bid, :bid_end, :b2c_publish, :b2c_product_buyer_details, :extend_b2c_time],
        "api/v1/warehouse/inventories": [:pending_grade, :item_info, :search_inventory, :rtv, :restock, :repair, :liquidation, :ewaste ,:rtv_email, :pending_issues, :alert_inventories, :disposition_criticality_count,:inventory_status_count, :bucket_alert_records, :get_dispositions, :assign_new_stn, :document_search, :update_serial_number, :search_items],
        "api/v1/warehouse/e_wastes": [:get_vendor_ewaste, :update_ewaste_cell, :fetch_e_wastes, :generate_csv, :search_item],
        "api/v1/warehouse/inward": [:get_sku_details, :create_inventory],
        "api/v1/warehouse/variation_reports": [:index],
        "api/v1/warehouse/warehouse_dispatch": [:index, :get_selected_gate_passes, :logistics, :create_consignment, :consignment_file_types],
        "admin/master_file_uploads": [:index, :create, :retry_upload],
        "api/v1/gradings": [:fetch_regrade_inventories, :category_rules, :calculate_grade, :store_grade, :send_images_to_ai, :update_ai_details],

        # "api/v1/warehouse/repairs": [:index , :pending_repair, :upload , :delete_images, :create_job_sheet],
        "api/v1/warehouse/new_repairs": [:index, :update_repair_details, :update_disposition_item, :search_item, :index_new, :get_filters_data, :show, :update_pending_quotation, :update_details, :create_dispatch_items, :get_vendor_master, :repair_dispatch_items, :get_dispositions, :update_disposition, :reject_disposition_item, :repair_dispatch_item],
        "api/v1/warehouse/return_to_vendor": [:index, :send_for_claim, :approve_reject_inventory, :send_reminder_or_escalation, :resubmit_inventories, :set_disposition, :send_for_escalation, :update_call_log, :update_inspection_details, :claim_settlement, :create_dispatch_items, :get_dispositions, :get_vendor_master, :edit_information, :set_disposition_on_claim, :search_item],
        "api/v1/warehouse/redeploy": [:index, :update_redeploy_details, :get_distribution_centers, :create_redeploy_dispatch_order, :get_vendor_redeploy, :search_item, :get_dispositions, :set_disposition],
        "api/v1/warehouse/restocks": [:index, :update_restock_details, :show, :create_restock_dispatch_order, :restock_dispatch_items, :get_master_vendor, :get_filters_data, :restock_dispatch_item],

        "api/v1/warehouse/put_away": [:index, :update_sub_location, :not_found, :request_reasons, :sub_locations, :write_off, :get_dispositions, :all_inventories, :filters_data, :export_inventory, :import_inventory],
        "api/v1/warehouse/put_requests": [:index, :create, :show, :update, :destroy, :cancel_request, :location_users, :update_assignee, :add_items, :mark_as_not_found, :filters_data],
        "api/v1/warehouse/sub_locations": [:index, :create, :show, :update, :get_locations, :bulk_delete, :sub_location_rules, :rule_types, :update_rules, :export_sublocations, :import_sublocations, :export_sublocation_sequence, :import_sublocation_sequence],
        "api/v1/warehouse/distribution_centers": [:index, :create, :show, :update, :sub_location_sequence, :update_sequence],
        "api/v1/warehouse/wms/put_away": [:index, :show, :get_sub_locations, :update_sub_location, :add_toat, :submit_request, :update_pick_up],

        "api/v1/warehouse/company_stocks": [:index, :create, :update, :destroy, :show, :upload_stock],

        "api/v1/warehouse/stock_transfers": [:index, :assign_disposition , :transfer, :update_rsto],
        
        "api/v1/warehouse/wms/gate_passes": [:index, :client_category_grading_rules, :disposition_rules, :update_inwarding_details, :create_inventories, :generate_tag, :return_reasons, :category_rules, :calculate_grade, :calculate_grade_new, :stn_search, :search_sku, :update_inventory, :proceed_grn, :update_grn, :serial_verification, :export_pending_grn_inventories, :get_grn_data, :export_inward_visibility_report, :export_outward_visibility_report, :timeline_report, :export_daily_report],

        "api/v1/warehouse/wms/stowing": [:fetch_inventories, :set_location, :complete_stowing, :unstowed_items],

        "api/v1/warehouse/markdowns": [:index, :get_distribution_center, :get_vendor_markdown, :markdown_update, :markdown_dispatch_complete, :search_item],
        "api/v1/warehouse/insurances": [:index, :submit_for_insurance, :update_call_log, :submit_inspection, :approve_reject_insurance, :set_disposition, :create_dispatch_items, :get_dispositions, :get_vendor_insurance, :search_item],
        "api/v1/warehouse/new_insurances": [:index, :show, :update_document, :update_claim_ticket, :update_inspection_details, :update_approval_details, :get_claim_decisions, :get_pending_documents, :bulk_update_docs, :get_dispositions, :update_disposition, :set_disposition, :update_claim_amount],
        "api/v1/warehouse/insurers": [:index, :new, :create, :show, :edit, :update, :destroy, :get_insurer_configs, :bulk_delete],
        "api/v1/warehouse/replacements": [:index, :get_dispositions, :submit_for_inspection, :submit_inspection, :approve_reject_replacement, :set_disposition, :create_replacement, :get_sku_records, :search_item, :show, :update_confirmation, :dispatch_items, :dispatch_item],
        "api/v1/warehouse/wms/pick": [:fetch_orders, :update_toat, :pick_confirm, :cancel_lot, :edit_lot, :remove_item_from_lot, :adjust_amount],
        "api/v1/warehouse/dispatch": [:fetch_orders, :create_pick_up_request, :create_packaging_request, :update_sub_location, :add_items, :write_off, :dispatch_boxes, :get_filters_data, :update_dispatch_details, :set_disposition, :get_dispositions],
        "api/v1/warehouse/wms/pack": [:fetch_orders, :assign_box, :create_box, :dispatch_confirm, :delete_box, :remove_item],
        "api/v1/warehouse/wms/dispatch": [:fetch_orders, :dispatch_initiate, :dispatch_initiate_new, :dispatch_complete, :close_beam_lot, :update_pick_up_request, :update_putaway_item, :add_box, :submit_pick_up_request, :submit_packaging_request, :index, :request_details, :pending_dispatch, :destination_based_boxes, :update_dispatch_details],
        "api/v1/warehouse/liquidation_file_uploads": [:index, :create],
        "api/v1/warehouse/e_waste_file_uploads": [:index, :create],
        "api/v1/warehouse/item_informations": [:search],  
        "api/v1/warehouse/e_waste_orders": [:index, :create_lot, :update_lot_status, :delete_lot, :winner_code_list],
        "api/v1/warehouse/liquidation_orders": [:index,:delete_lot, :relive_lot, :winner_code_list, :lot_inventory, :beam_orders, :publish_lot, :get_lot_details, :extend_lot_mail, :extend_time, :cancel_lot_mail, :send_email_to_vendors, :get_quotations, :update_lot_beam_status, :approve_contract_lot, :get_contracted_price],
        "api/v1/warehouse/pending_dispositions": [:index, :set_disposition, :get_dispositions, :search_item],
        "api/v1/warehouse/inventory_file_uploads": [:index, :create, :update, :get_edit_lot_images],
        "api/v1/warehouse/users": [:index, :fetch_all_info, :create, :show, :update, :destroy, :restore_user],
        "api/v1/warehouse/alert_inventories": [:index],
        "api/v1/warehouse/manual_processes": [:bucket_movement, :delete_item, :get_dispositions],
        "api/v1/warehouse/third_party_claims": [:index, :get_filters_data, :update_cn_dn_number, :show],
        "api/v1/warehouse/return_initiation/return_creation_file_uploads": [:index, :create, :show, :update, :destroy, :edit],
        "api/v1/warehouse/return_initiation/return_creations": [:index, :create, :show, :update, :destroy, :edit, :search, :delete_return_items, :create_return_items],
        "api/v1/warehouse/return_initiation/return_items": [:index, :create, :show, :update, :destroy, :edit],
        "api/v1/warehouse/return_initiation/return_eligibility_validations": [:index, :create, :show, :update, :destroy, :edit, :approve, :reject, :search],
        "api/v1/warehouse/return_initiation/return_manual_dispositions": [:index, :create, :show, :update, :destroy, :edit, :search, :assign_disposition],
        "api/v1/warehouse/return_initiation/return_approvals": [:index, :get_settlement_methods, :get_enums_data, :approve_sales_return, :reject_sales_return, :approve_internal_return, :reject_internal_return, :approve_exchange_return, :approve_warranty_return, :approve_lease_return, :reject_return_item, :reject_warranty_return],
        "api/v1/warehouse/return_initiation/reverse_pickup": [:index, :update_tag_numbers, :update_packaging_details, :reverse_pickup_items, :update_pickup_date, :assign_logistic_partner, :update_pickup_details, :import_dc_locations],
        "api/v1/warehouse/prd": [:index, :show, :update, :filters_data, :delete_items, :get_irrd_items, :get_ird_items, :download_items, :download_irrd_items, :download_ird_items, :upload_file, :file_uploads, :download_prd_sample, :update_approval, :reject],
        "api/v1/warehouse/brand_call_logs": [:index, :show, :update_document, :update_ticket, :update_inspection_details, :update_approval_details, :get_brand_decisions, :get_pending_documents, :bulk_update_docs, :get_dispositions, :update_disposition, :set_disposition, :update_claim_amount],
        "api/v2/warehouse/saleables": [:index, :show, :item_details, :reserve_items, :un_reserve, :update_payment_details, :get_payment_details, :get_buyers, :create_buyer, :update_disposition, :get_city_and_states, :dispositions, :set_dispositions],
        "api/v2/warehouse/inventory_file_uploads": [:index, :create, :download_competitive_liquidations],
        "api/v2/account_settings": [:show],
        "api/v1/physical_inspections": [:index, :create, :scan_inventories, :update_status, :update_assignees, :brands, :articles, :categories, :dispositions, :assignees, :issue_items, :get_sub_locations],
        "api/v1/issue_inventories": [:index, :update_status, :pending_approvals, :reject, :correct_excess, :approve, :get_filter_locations],
        "api/v1/scan_inventories": [:show],
        "api/v1/transfer_inventories": [:index, :dispositions_type, :dispositions, :dispositions_sub_status, :transfer_inventories],
        "api/v1/forward/replacements": [:index, :show, :item_details, :reserve, :reserve_items, :un_reserve, :update_payment_details, :get_payment_details, :get_buyers, :get_dispositions, :set_disposition],
        "api/v1/forward/demos": [:index, :show, :get_dispositions, :set_disposition, :get_locations, :transfer],
        "api/v1/forward/productions": [:index, :filters_data, :get_dispositions, :set_disposition, :update_production_inventory, :get_finished_articles, :bom_details, :item_details, :update_item, :knit_items],
        "api/v2/warehouse/ecom_liquidations": [:dispatch_orders],
        "api/v1/warehouse/consignment": [:get_logistics_partners, :generate_receipt_summary, :submit_consignment_details],
        "api/v1/warehouse/item_inward": [:prd_info, :auto_inward, :get_box_items, :grading_questions, :compute_grade, :update_tag_number, :complete_ird, :fetch_item, :generate_grn],
        "api/v1/warehouse/inward_tracking": [:index, :show, :generate_grn],
        "api/v1/warehouse/cannibalization/to_be_cannibalized": [:index, :generate_tag_number, :move_to_cannibalized, :get_bom, :move_to_work_in_progress],
        "api/v2/warehouse/cannibalization/to_be_cannibalized": [:index, :get_dispositions, :generate_tag_number, :move_to_cannibalized, :get_bom, :move_to_work_in_progress, :change_disposition],
        "api/v2/warehouse/cannibalization/work_in_progress": [:index],
        "api/v2/warehouse/cannibalization/cannibalized": [:index, :get_dispositions, :change_disposition],
        "api/v2/warehouse/return_inventories": [:inventories, :show, :create, :update_record],
        "api/v2/warehouse/oms/forward/purchase_orders": [:index, :create, :show, :items, :vendors, :inventories_data, :locations, :detail],
        "api/v2/warehouse/order_management_systems": [:index, :create, :show, :items],
        "api/v2/warehouse/oms/reverse/sales_orders": [:index, :create, :show, :items, :vendor_details, :location_details, :article_id_list, :article_description_list, :item_details, :create_invoice, :cancel_order, :print_order],
        "api/v2/warehouse/oms/reverse/back_orders": [:index, :create, :show, :item_details, :move_to_so, :cancel_order, :items, :print_order, :print_order],
        "api/v2/warehouse/oms/reverse/lease_orders": [:index, :create, :show, :items, :vendor_details, :location_details, :article_id_list, :article_description_list, :item_details, :cancel_order, :print_order],
        "api/v2/warehouse/oms/reverse/transfer_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/repair_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/replacement_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/replacement_customer_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/outward_return_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/forward/purchase_order_receipt_challans": [:index, :create, :details]
      },

      site_admin: {  #role as key
        "api/v1/warehouse/gate_passes": [:fetch_gate_passes, :create_consignment_box, :update_box_detail, :complete_consignment, :get_box_conditions, :consignment_box_file_types, :import],
        "api/v1/warehouse/warehouse_grading": [:category_rules, :upload, :generate_rr, :finalize_grading , :warehouse_rules, :delete_images],
        "api/v1/store/returns/customer_returns": [:category_rules, :upload, :generate_rr, :finalize_grading],
        "api/v1/warehouse/item_inward": [:prd_info, :auto_inward, :get_box_items, :grading_questions, :compute_grade, :update_tag_number, :complete_ird, :fetch_item, :generate_grn],
        "api/v1/lookups": [:get_customer_return_reasons, :get_warehouse_reasons],
        "api/v1/warehouse/quality_control": [:fetch_inventories, :complete_qc],
        "api/v1/warehouse/stowing": [:fetch_inventories, :set_location, :complete_stowing],
        "api/v1/warehouse/users": [:index, :fetch_all_info, :create, :show, :update, :destroy, :restore_user],
        "api/v1/warehouse/pending_packaging": [:index, :get_inventories, :create_box, :generate_gate_pass, :create_items, :delete_packaging_box],
        "api/v1/warehouse/pick_item": [:index, :get_inventories, :create_items],
        "api/v1/warehouse/liquidations": [:get_vendor_liquidation, :search_vendor, :update_lot_order, :update_liquidation_cell, :fetch_inventories, :generate_csv, :create_lots, :create_manual_dispatch_lot, :dispatch_offline_lot, :regrade_inventories , :moving_lot_creation, :fetch_pending_regrading_inventories, :get_liquidation_requests, :move_to_pending_liquidation, :fetch_beam_inventories, :create_beam_lots, :create_beam_republish_lots, :create_contract_lots, :get_liquidation_images, :get_republish_liquidation_images, :get_quotations, :get_email_vendors_list, :update_lot_winner, :get_liquidation_images_page, :remove_excess_items_before_dispatch, :search_item, :get_dispositions, :set_disposition, :get_vendor_contract],
        "api/v2/warehouse/liquidation/channel_allocations": [:index, :mark_e_waste, :category_list, :formatted_category_list, :allocate_channel],
        "api/v2/warehouse/liquidation/price_discovery": [:index, :assign_price],
        "api/v2/warehouse/liquidation/competitive_bidding_price": [:index, :create_lot, :move_to_moq, :buyers, :inventories_images, :calculate_ai_price],
        "api/v2/warehouse/liquidation/contracted_price": [:index, :create_lot, :get_vendor_contract],
        "api/v2/warehouse/liquidation/moq": [:index, :create_lot, :move_to_competative_bidding, :article_id_list, :article_description_list, :liquidation_quantity_based_on_grade, :buyers, :mrp_per_lot],
        "api/v2/warehouse/liquidation/b2c_pending_publish": [:index, :move_to_b2b, :publish, :get_platform_list, :resync_publish],
        "api/v2/warehouse/liquidation/moq": [:index],
        "api/v2/warehouse/liquidation_order/b2b/in_progress": [:index, :show, :update, :vendor_list, :reserve, :update_timing, :delete_lots],
        "api/v2/warehouse/liquidation_order/b2b/pending_publish": [:index, :show, :update, :publish, :update_timing, :lot_details, :lot_images, :delete_lots, :remove_lot_items, :index_new],
        "api/v2/warehouse/liquidation_order/b2c/in_progress": [:index, :delete_lots, :update_sales],
        "api/v2/warehouse/liquidation_order/b2c/pending_publish": [:index, :publish],
        "api/v2/warehouse/liquidation_order/pending/decision": [:index, :update, :get_bidders, :republish, :delete_lots],
        "api/v2/warehouse/liquidation_order/pending/b2c_decision": [:index],
        "api/v2/warehouse/liquidation_order/pending/dispatch_confirmation_time": [:index, :update_dispatch_date],
        "api/v2/warehouse/liquidation_order/pending/payment": [:index, :update, :unreserve_sub_lot],
        "api/v2/warehouse/vendor_return/pending_confirmation": [:index, :update_confirmation, :vendor_list, :brand_list],
        "api/v2/warehouse/vendor_return/dispatch": [:index],
        "api/v2/warehouse/liquidation_order/dispatch": [:index],
        "api/v2/warehouse/markdown/pending_price_and_location": [:index, :update_markdowns, :filter_categories, :filter_grade, :get_distribution_center],
        "api/v2/warehouse/markdown/dispatch": [:index],
        "api/v2/warehouse/capital_assets": [:index, :get_distribution_users, :assigned_user, :unassigned_user, :get_dispositions, :set_dispositions],
        "api/v2/warehouse/rental/reserve": [:index, :create_rental_reserve, :article_ids_with_quantity, :vendor_master_details, :get_dispositions, :change_disposition],
        "api/v2/warehouse/rental/pending_payment": [:index, :update_status, :unreserve],
        "api/v2/warehouse/rental/out_for_rental": [:index, :update_rental],
        "api/v2/warehouse/callbacks": [:publish, :place_bid, :buy_now, :extend_bid, :bid_end, :b2c_publish, :b2c_product_buyer_details, :extend_b2c_time],
        "api/v1/warehouse/inventories": [:pending_grade, :item_info, :search_inventory, :rtv, :restock, :repair, :liquidation, :ewaste ,:rtv_email, :pending_issues, :alert_inventories, :disposition_criticality_count,:inventory_status_count, :bucket_alert_records, :get_dispositions, :assign_new_stn, :document_search, :update_serial_number, :search_items],
        "api/v1/warehouse/e_wastes": [:get_vendor_ewaste, :update_ewaste_cell, :fetch_e_wastes, :generate_csv, :search_item],
        "api/v1/warehouse/inward": [:get_sku_details, :create_inventory],
        "api/v1/warehouse/variation_reports": [:index],
        "api/v1/warehouse/warehouse_dispatch": [:index, :get_selected_gate_passes, :logistics, :create_consignment, :consignment_file_types],
        "admin/master_file_uploads": [:index, :create, :retry_upload],
        "admin/return_inventory_informations": [:index, :create, :update, :destroy, :show],
        "api/v1/warehouse/return_initiation/return_inventory_informations": [:index, :create, :show, :update, :destroy, :edit, :search_return_items],
        "api/v1/gradings": [:fetch_regrade_inventories, :category_rules, :calculate_grade, :store_grade, :send_images_to_ai, :update_ai_details],
        "api/v2/dashboard": [:ai_discrepancy_reports, :ai_discrepancy_report],

        # "api/v1/warehouse/repairs": [:index , :pending_repair, :upload , :delete_images, :create_job_sheet],
        "api/v1/warehouse/new_repairs": [:index, :update_repair_details, :update_disposition_item, :search_item, :index_new, :get_filters_data, :show, :update_pending_quotation, :update_details, :create_dispatch_items, :get_vendor_master, :repair_dispatch_items, :get_dispositions, :update_disposition, :reject_disposition_item, :repair_dispatch_item],
        "api/v1/warehouse/return_to_vendor": [:index, :send_for_claim, :approve_reject_inventory, :send_reminder_or_escalation, :resubmit_inventories, :set_disposition, :send_for_escalation, :update_call_log, :update_inspection_details, :claim_settlement, :create_dispatch_items, :get_dispositions, :get_vendor_master, :edit_information, :set_disposition_on_claim, :search_item],
        "api/v1/warehouse/redeploy": [:index, :update_redeploy_details, :get_distribution_centers, :create_redeploy_dispatch_order, :get_vendor_redeploy, :search_item, :get_dispositions, :set_disposition],
        "api/v1/warehouse/restocks": [:index, :update_restock_details, :show, :create_restock_dispatch_order, :restock_dispatch_items, :get_master_vendor, :get_filters_data, :restock_dispatch_item],

        "api/v1/warehouse/put_away": [:index, :update_sub_location, :not_found, :request_reasons, :sub_locations, :write_off, :get_dispositions, :all_inventories, :filters_data, :export_inventory, :import_inventory],
        "api/v1/warehouse/put_requests": [:index, :create, :show, :update, :destroy, :cancel_request, :location_users, :update_assignee, :add_items, :mark_as_not_found],
        "api/v1/warehouse/wms/put_away": [:index, :show, :get_sub_locations, :update_sub_location, :add_toat, :submit_request, :update_pick_up],

        "api/v1/warehouse/company_stocks": [:index, :create, :update, :destroy, :show, :upload_stock],

        "api/v1/warehouse/stock_transfers": [:index, :assign_disposition , :transfer, :update_rsto],
        
        "api/v1/warehouse/wms/gate_passes": [:index, :client_category_grading_rules, :disposition_rules, :update_inwarding_details, :create_inventories, :generate_tag, :return_reasons, :category_rules, :calculate_grade, :calculate_grade_new, :stn_search, :search_sku, :update_inventory, :proceed_grn, :update_grn, :serial_verification, :export_pending_grn_inventories, :get_grn_data, :export_inward_visibility_report, :export_outward_visibility_report, :timeline_report, :export_daily_report],

        "api/v1/warehouse/wms/stowing": [:fetch_inventories, :set_location, :complete_stowing, :unstowed_items],

        "api/v1/warehouse/markdowns": [:index, :get_distribution_center, :get_vendor_markdown, :markdown_update, :markdown_dispatch_complete, :search_item],
        "api/v1/warehouse/insurances": [:index, :submit_for_insurance, :update_call_log, :submit_inspection, :approve_reject_insurance, :set_disposition, :create_dispatch_items, :get_dispositions, :get_vendor_insurance, :search_item],
        "api/v1/warehouse/new_insurances": [:index, :show, :update_document, :update_claim_ticket, :update_inspection_details, :update_approval_details, :get_claim_decisions, :get_pending_documents, :bulk_update_docs, :get_dispositions, :update_disposition, :set_disposition],
        "api/v1/warehouse/insurers": [:index, :new, :create, :show, :edit, :update, :destroy, :get_insurer_configs, :bulk_delete],
        "api/v1/warehouse/replacements": [:index, :get_dispositions, :submit_for_inspection, :submit_inspection, :approve_reject_replacement, :set_disposition, :create_replacement, :get_sku_records, :search_item, :show, :update_confirmation, :dispatch_items, :dispatch_item],
        "api/v1/warehouse/wms/pick": [:fetch_orders, :update_toat, :pick_confirm, :cancel_lot, :edit_lot, :remove_item_from_lot, :adjust_amount],
        "api/v1/warehouse/dispatch": [:fetch_orders, :create_pick_up_request, :create_packaging_request, :update_sub_location],
        "api/v1/warehouse/wms/pack": [:fetch_orders, :assign_box, :create_box, :dispatch_confirm, :delete_box, :remove_item],
        "api/v1/warehouse/wms/dispatch": [:fetch_orders, :dispatch_initiate, :dispatch_initiate_new, :dispatch_complete, :close_beam_lot, :update_pick_up_request, :update_putaway_item, :add_box, :submit_packaging_request, :index, :request_details, :destination_based_boxes, :update_dispatch_details],
        "api/v1/warehouse/liquidation_file_uploads": [:index, :create],
        "api/v1/warehouse/e_waste_file_uploads": [:index, :create],
        "api/v1/warehouse/item_informations": [:search],  
        "api/v1/warehouse/e_waste_orders": [:index, :create_lot, :update_lot_status, :delete_lot, :winner_code_list],
        "api/v1/warehouse/liquidation_orders": [:index,:delete_lot, :relive_lot, :winner_code_list, :lot_inventory, :beam_orders, :publish_lot, :get_lot_details, :extend_lot_mail, :extend_time, :cancel_lot_mail, :send_email_to_vendors, :get_quotations, :update_lot_beam_status, :approve_contract_lot, :get_contracted_price],
        "api/v1/warehouse/pending_dispositions": [:index, :set_disposition, :get_dispositions, :search_item],
        "api/v1/warehouse/inventory_file_uploads": [:index, :create, :update, :get_edit_lot_images],
        "api/v1/warehouse/alert_inventories": [:index],
        "api/v1/warehouse/users": [:index, :fetch_all_info, :create, :show, :update, :destroy, :restore_user],
        "api/v1/warehouse/alert_inventories": [:index],
        "api/v1/warehouse/return_initiation/return_creation_file_uploads": [:index, :create, :show, :update, :destroy, :edit],
        "api/v1/warehouse/return_initiation/return_creations": [:index, :create, :show, :update, :destroy, :edit, :search, :delete_return_items, :create_return_items],
        "api/v1/warehouse/return_initiation/return_items": [:index, :create, :show, :update, :destroy, :edit, :search],
        "api/v1/warehouse/return_initiation/return_eligibility_validations": [:index, :create, :show, :update, :destroy, :edit, :approve, :reject, :search],
        "api/v1/warehouse/return_initiation/return_manual_dispositions": [:index, :create, :show, :update, :destroy, :edit, :search, :assign_disposition],
        "api/v1/warehouse/manual_processes": [:bucket_movement, :delete_item, :get_dispositions],
        "api/v2/warehouse/saleables": [:index, :show, :item_details, :reserve_items, :un_reserve, :update_payment_details, :get_payment_details, :get_buyers, :create_buyer, :update_disposition, :get_city_and_states, :dispositions, :set_dispositions],
        "api/v2/warehouse/inventory_file_uploads": [:index, :create, :download_competitive_liquidations],
        "api/v2/account_settings": [:show],
        "api/v1/transfer_inventories": [:index, :dispositions_type, :dispositions, :dispositions_sub_status, :transfer_inventories],
        "api/v2/warehouse/ecom_liquidations": [:dispatch_orders],
        "api/v1/warehouse/cannibalization/to_be_cannibalized": [:index, :generate_tag_number, :move_to_cannibalized, :get_bom, :move_to_work_in_progress],
        "api/v2/warehouse/cannibalization/to_be_cannibalized": [:index, :get_dispositions, :generate_tag_number, :move_to_cannibalized, :get_bom, :move_to_work_in_progress, :change_disposition],
        "api/v2/warehouse/cannibalization/work_in_progress": [:index],
        "api/v2/warehouse/cannibalization/cannibalized": [:index, :get_dispositions, :change_disposition],
        "api/v2/warehouse/return_inventories": [:inventories, :show, :create, :update_record],
        "api/v2/warehouse/oms/forward/purchase_orders": [:index, :create, :show, :items, :vendors, :inventories_data, :locations, :detail],
        "api/v2/warehouse/order_management_systems": [:index, :create, :show, :items],
        "api/v2/warehouse/oms/reverse/sales_orders": [:index, :create, :show, :items, :vendor_details, :location_details, :article_id_list, :article_description_list, :item_details, :create_invoice, :cancel_order, :print_order],
        "api/v2/warehouse/oms/reverse/back_orders": [:index, :create, :show, :item_details, :move_to_so, :cancel_order, :items, :print_order, :print_order],
        "api/v2/warehouse/oms/reverse/lease_orders": [:index, :create, :show, :items, :vendor_details, :location_details, :article_id_list, :article_description_list, :item_details, :cancel_order, :print_order],
        "api/v2/warehouse/oms/reverse/transfer_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/repair_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/replacement_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/replacement_customer_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/outward_return_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/forward/purchase_order_receipt_challans": [:index, :create, :details]
      },

      default_user: { 
        "api/v1/warehouse/gate_passes": [:fetch_gate_passes, :create_consignment_box, :update_box_detail, :complete_consignment, :get_box_conditions, :consignment_box_file_types, :import],
        "api/v1/warehouse/warehouse_grading": [:category_rules, :upload, :generate_rr, :finalize_grading , :warehouse_rules, :delete_images],
        "api/v1/store/returns/customer_returns": [:category_rules, :upload, :generate_rr, :finalize_grading],
        "api/v1/warehouse/item_inward": [:prd_info, :auto_inward, :get_box_items, :grading_questions, :compute_grade, :update_tag_number, :complete_ird, :fetch_item, :generate_grn],
        "api/v1/lookups": [:get_customer_return_reasons, :get_warehouse_reasons],
        "api/v1/warehouse/quality_control": [:fetch_inventories, :complete_qc],
        "api/v1/warehouse/stowing": [:fetch_inventories, :set_location, :complete_stowing],
        "api/v1/warehouse/users": [:index, :fetch_all_info, :create, :show, :update, :destroy, :restore_user],
        "api/v1/warehouse/pending_packaging": [:index, :get_inventories, :create_box, :generate_gate_pass, :create_items, :delete_packaging_box],
        "api/v1/warehouse/pick_item": [:index, :get_inventories, :create_items],
        "api/v1/warehouse/liquidations": [:get_vendor_liquidation, :search_vendor, :update_lot_order, :update_liquidation_cell, :fetch_inventories, :generate_csv, :create_lots, :create_manual_dispatch_lot, :dispatch_offline_lot, :regrade_inventories , :moving_lot_creation, :fetch_pending_regrading_inventories, :get_liquidation_requests, :move_to_pending_liquidation, :fetch_beam_inventories, :create_beam_lots, :create_beam_republish_lots, :create_contract_lots, :get_liquidation_images, :get_republish_liquidation_images, :get_quotations, :get_email_vendors_list, :update_lot_winner, :get_liquidation_images_page, :remove_excess_items_before_dispatch, :search_item, :get_dispositions, :set_disposition, :get_vendor_contract],
        "api/v2/warehouse/liquidation/channel_allocations": [:index, :mark_e_waste, :category_list, :formatted_category_list, :allocate_channel],
        "api/v2/warehouse/liquidation/price_discovery": [:index, :assign_price],
        "api/v2/warehouse/liquidation/competitive_bidding_price": [:index, :create_lot, :move_to_moq, :buyers, :inventories_images, :calculate_ai_price],
        "api/v2/warehouse/liquidation/contracted_price": [:index, :create_lot, :get_vendor_contract],
        "api/v2/warehouse/liquidation/moq": [:index, :create_lot, :move_to_competative_bidding, :article_id_list, :article_description_list, :liquidation_quantity_based_on_grade, :buyers, :mrp_per_lot],
        "api/v2/warehouse/liquidation/b2c_pending_publish": [:index, :move_to_b2b, :publish, :get_platform_list, :resync_publish],
        "api/v2/warehouse/liquidation_order/b2b/in_progress": [:index, :show, :update, :vendor_list, :reserve, :update_timing, :delete_lots],
        "api/v2/warehouse/liquidation_order/b2b/pending_publish": [:index, :show, :update, :publish, :update_timing, :lot_details, :lot_images, :delete_lots, :remove_lot_items, :index_new],
        "api/v2/warehouse/liquidation_order/b2c/in_progress": [:index, :delete_lots, :update_sales],
        "api/v2/warehouse/liquidation_order/b2c/pending_publish": [:index, :publish],
        "api/v2/warehouse/liquidation_order/pending/decision": [:index, :update, :get_bidders, :republish, :delete_lots],
        "api/v2/warehouse/liquidation_order/pending/b2c_decision": [:index],
        "api/v2/warehouse/liquidation_order/pending/dispatch_confirmation_time": [:index, :update_dispatch_date],
        "api/v2/warehouse/liquidation_order/pending/payment": [:index, :update, :unreserve_sub_lot],
        "api/v2/warehouse/vendor_return/pending_confirmation": [:index, :update_confirmation, :vendor_list, :brand_list],
        "api/v2/warehouse/vendor_return/dispatch": [:index],
        "api/v2/warehouse/liquidation_order/dispatch": [:index],
        "api/v2/warehouse/markdown/pending_price_and_location": [:index, :update_markdowns, :filter_categories, :filter_grade, :get_distribution_center],
        "api/v2/warehouse/markdown/dispatch": [:index],
        "api/v2/warehouse/capital_assets": [:index, :get_distribution_users, :assigned_user, :unassigned_user, :get_dispositions, :set_dispositions],
        "api/v2/warehouse/rental/reserve": [:index, :create_rental_reserve, :article_ids_with_quantity, :vendor_master_details, :get_dispositions, :change_disposition],
        "api/v2/warehouse/rental/pending_payment": [:index, :update_status, :unreserve],
        "api/v2/warehouse/rental/out_for_rental": [:index, :update_rental],
        "api/v2/warehouse/callbacks": [:publish, :place_bid, :buy_now, :extend_bid, :bid_end, :b2c_publish, :b2c_product_buyer_details, :extend_b2c_time],
        "api/v1/warehouse/inventories": [:pending_grade, :item_info, :search_inventory, :rtv, :restock, :repair, :liquidation, :ewaste ,:rtv_email, :pending_issues, :alert_inventories, :disposition_criticality_count,:inventory_status_count, :bucket_alert_records, :get_dispositions, :assign_new_stn, :document_search, :update_serial_number, :search_items],
        "api/v1/warehouse/e_wastes": [:get_vendor_ewaste, :update_ewaste_cell, :fetch_e_wastes, :generate_csv, :search_item],
        "api/v1/warehouse/inward": [:get_sku_details, :create_inventory],
        "api/v1/warehouse/variation_reports": [:index],
        "api/v1/warehouse/warehouse_dispatch": [:index, :get_selected_gate_passes, :logistics, :create_consignment, :consignment_file_types],
        "admin/master_file_uploads": [:index, :create, :retry_upload],
        "api/v1/gradings": [:fetch_regrade_inventories, :category_rules, :calculate_grade, :store_grade, :send_images_to_ai, :update_ai_details],

        # "api/v1/warehouse/repairs": [:index , :pending_repair, :upload , :delete_images, :create_job_sheet],
        "api/v1/warehouse/new_repairs": [:index, :update_repair_details, :search_item, :index_new, :get_filters_data, :show, :update_pending_quotation, :update_details, :create_dispatch_items, :get_vendor_master, :repair_dispatch_items, :get_dispositions, :update_disposition, :repair_dispatch_item],
        "api/v1/warehouse/return_to_vendor": [:index, :send_for_claim, :approve_reject_inventory, :send_reminder_or_escalation, :resubmit_inventories, :set_disposition, :send_for_escalation, :update_call_log, :update_inspection_details, :claim_settlement, :create_dispatch_items, :get_dispositions, :get_vendor_master, :edit_information, :set_disposition_on_claim, :search_item],
        "api/v1/warehouse/redeploy": [:index, :update_redeploy_details, :get_distribution_centers, :create_redeploy_dispatch_order, :get_vendor_redeploy, :search_item, :get_dispositions, :set_disposition],
        "api/v1/warehouse/restocks": [:index, :update_restock_details, :show, :create_restock_dispatch_order, :restock_dispatch_items, :get_master_vendor, :get_filters_data, :restock_dispatch_item],

        "api/v1/warehouse/put_away": [:index, :update_sub_location, :not_found, :request_reasons, :sub_locations, :write_off, :get_dispositions, :all_inventories, :filters_data, :export_inventory, :import_inventory],
        "api/v1/warehouse/put_requests": [:index, :create, :show, :update, :destroy, :cancel_request, :location_users, :update_assignee, :add_items, :mark_as_not_found, :filters_data],
        "api/v1/warehouse/sub_locations": [:index, :create, :show, :update, :get_locations, :bulk_delete, :sub_location_rules, :rule_types, :update_rules, :export_sublocations, :import_sublocations, :export_sublocation_sequence, :import_sublocation_sequence],
        "api/v1/warehouse/distribution_centers": [:index, :create, :show, :update, :sub_location_sequence, :update_sequence],
        "api/v1/warehouse/wms/put_away": [:index, :show, :get_sub_locations, :update_sub_location, :add_toat, :submit_request, :update_pick_up],

        "api/v1/warehouse/company_stocks": [:index, :create, :update, :destroy, :show, :upload_stock],

        "api/v1/warehouse/stock_transfers": [:index, :assign_disposition , :transfer, :update_rsto],
        
        "api/v1/warehouse/wms/gate_passes": [:index, :client_category_grading_rules, :disposition_rules, :update_inwarding_details, :create_inventories, :generate_tag, :return_reasons, :category_rules, :calculate_grade, :calculate_grade_new, :stn_search, :search_sku, :update_inventory, :proceed_grn, :update_grn, :serial_verification, :export_pending_grn_inventories, :get_grn_data, :export_inward_visibility_report, :export_outward_visibility_report, :timeline_report, :export_daily_report],

        "api/v1/warehouse/wms/stowing": [:fetch_inventories, :set_location, :complete_stowing, :unstowed_items],

        "api/v1/warehouse/markdowns": [:index, :get_distribution_center, :get_vendor_markdown, :markdown_update, :markdown_dispatch_complete, :search_item],
        "api/v1/warehouse/insurances": [:index, :submit_for_insurance, :update_call_log, :submit_inspection, :approve_reject_insurance, :set_disposition, :create_dispatch_items, :get_dispositions, :get_vendor_insurance, :search_item],
        "api/v1/warehouse/new_insurances": [:index, :show, :update_document, :update_claim_ticket, :update_inspection_details, :update_approval_details, :get_claim_decisions, :get_pending_documents, :bulk_update_docs, :get_dispositions, :update_disposition, :set_disposition, :update_claim_amount],
        "api/v1/warehouse/insurers": [:index, :new, :create, :show, :edit, :update, :destroy, :get_insurer_configs, :bulk_delete],
        "api/v1/warehouse/replacements": [:index, :get_dispositions, :submit_for_inspection, :submit_inspection, :approve_reject_replacement, :set_disposition, :create_replacement, :get_sku_records, :search_item, :show, :update_confirmation, :dispatch_items, :dispatch_item],
        "api/v1/warehouse/wms/pick": [:fetch_orders, :update_toat, :pick_confirm, :cancel_lot, :edit_lot, :remove_item_from_lot, :adjust_amount],
        "api/v1/warehouse/dispatch": [:fetch_orders, :create_pick_up_request, :create_packaging_request, :update_sub_location, :add_items, :write_off, :dispatch_boxes, :get_filters_data, :update_dispatch_details, :set_disposition, :get_dispositions],
        "api/v1/warehouse/wms/pack": [:fetch_orders, :assign_box, :create_box, :dispatch_confirm, :delete_box, :remove_item],
        "api/v1/warehouse/wms/dispatch": [:fetch_orders, :dispatch_initiate, :dispatch_initiate_new, :dispatch_complete, :close_beam_lot, :update_pick_up_request, :update_putaway_item, :add_box, :submit_packaging_request, :index, :request_details, :destination_based_boxes, :update_dispatch_details],
        "api/v1/warehouse/liquidation_file_uploads": [:index, :create],
        "api/v1/warehouse/e_waste_file_uploads": [:index, :create],
        "api/v1/warehouse/item_informations": [:search],  
        "api/v1/warehouse/e_waste_orders": [:index, :create_lot, :update_lot_status, :delete_lot, :winner_code_list],
        "api/v1/warehouse/liquidation_orders": [:index,:delete_lot, :relive_lot, :winner_code_list, :lot_inventory, :beam_orders, :publish_lot, :get_lot_details, :extend_lot_mail, :extend_time, :cancel_lot_mail, :send_email_to_vendors, :get_quotations, :update_lot_beam_status, :approve_contract_lot, :get_contracted_price],
        "api/v1/warehouse/pending_dispositions": [:index, :set_disposition, :get_dispositions, :search_item],
        "api/v1/warehouse/inventory_file_uploads": [:index, :create, :update, :get_edit_lot_images],
        "api/v1/warehouse/wms/documents": [:search, :ean_search],
        "api/v1/warehouse/users": [:index, :fetch_all_info, :create, :show, :update, :destroy, :restore_user],
        "api/v1/warehouse/alert_inventories": [:index],
        "api/v1/warehouse/manual_processes": [:bucket_movement, :delete_item, :get_dispositions],
        "api/v1/warehouse/return_initiation/return_inventory_informations": [:index, :create, :show, :update, :destroy, :edit, :search_return_items, :create_return_items],
        "api/v1/warehouse/return_initiation/return_creation_file_uploads": [:index, :create, :show, :update, :destroy, :edit],
        "api/v1/warehouse/return_initiation/return_creations": [:index, :create, :show, :update, :destroy, :edit, :search, :delete_return_items, :create_return_items],
        "api/v1/warehouse/return_initiation/return_items": [:index, :create, :show, :update, :destroy, :edit],
        "api/v1/warehouse/return_initiation/return_eligibility_validations": [:index, :create, :show, :update, :destroy, :edit, :approve, :reject, :search],
        "api/v1/warehouse/return_initiation/return_manual_dispositions": [:index, :create, :show, :update, :destroy, :edit, :search, :assign_disposition],
        "api/v1/warehouse/brand_call_logs": [:index, :show, :update_document, :update_ticket, :update_inspection_details, :update_approval_details, :get_brand_decisions, :get_pending_documents, :bulk_update_docs, :get_dispositions, :update_disposition, :set_disposition, :update_claim_amount],
        "api/v1/warehouse/third_party_claims": [:index, :get_filters_data, :update_cn_dn_number, :show],
        "api/v2/warehouse/saleables": [:index, :show, :item_details, :reserve_items, :un_reserve, :update_payment_details, :get_payment_details, :get_buyers, :create_buyer, :update_disposition, :get_city_and_states, :dispositions, :set_dispositions],
        "api/v2/warehouse/inventory_file_uploads": [:index, :create, :download_competitive_liquidations],
        "api/v2/account_settings": [:show],
        "api/v1/transfer_inventories": [:index, :dispositions_type, :dispositions, :dispositions_sub_status, :transfer_inventories],
        "api/v2/warehouse/ecom_liquidations": [:dispatch_orders],
        "api/v1/warehouse/cannibalization/to_be_cannibalized": [:index, :generate_tag_number, :move_to_cannibalized, :get_bom, :move_to_work_in_progress],
        "api/v2/warehouse/cannibalization/to_be_cannibalized": [:index, :get_dispositions, :generate_tag_number, :move_to_cannibalized, :get_bom, :move_to_work_in_progress, :change_disposition],
        "api/v2/warehouse/cannibalization/work_in_progress": [:index],
        "api/v2/warehouse/cannibalization/cannibalized": [:index, :get_dispositions, :change_disposition],
        "api/v2/warehouse/return_inventories": [:inventories, :show, :create, :update_record],
        "api/v2/warehouse/oms/forward/purchase_orders": [:index, :create, :show, :items, :vendors, :inventories_data, :locations, :detail],
        "api/v2/warehouse/order_management_systems": [:index, :create, :show, :items],
        "api/v2/warehouse/oms/reverse/sales_orders": [:index, :create, :show, :items, :vendor_details, :location_details, :article_id_list, :article_description_list, :item_details, :create_invoice, :cancel_order, :print_order],
        "api/v2/warehouse/oms/reverse/back_orders": [:index, :create, :show, :item_details, :move_to_so, :cancel_order, :items, :print_order, :print_order],
        "api/v2/warehouse/oms/reverse/lease_orders": [:index, :create, :show, :items, :vendor_details, :location_details, :article_id_list, :article_description_list, :item_details, :cancel_order, :print_order],
        "api/v2/warehouse/oms/reverse/transfer_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/repair_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/replacement_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/replacement_customer_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/reverse/outward_return_orders": [:index, :create, :show, :item_details, :cancel_order, :items, :print_order],
        "api/v2/warehouse/oms/forward/purchase_order_receipt_challans": [:index, :create, :details]
      },

      physical_inspection_manager: {
        "api/v1/physical_inspections": [:index, :create, :scan_inventories, :update_status, :update_assignees, :brands, :articles, :categories, :dispositions, :assignees, :issue_items, :get_sub_locations],
        "api/v1/issue_inventories": [:index, :update_status, :pending_approvals, :reject, :correct_excess, :approve, :get_filter_locations],
        "api/v1/scan_inventories": [:show]
      },
      physical_inspection_executive: {
        "api/v1/physical_inspections": [:index, :create, :scan_inventories, :update_status, :update_assignees, :brands, :articles, :categories, :dispositions, :assignees, :issue_items, :get_sub_locations],
        "api/v1/scan_inventories": [:show]
      }

    }
  end

  def check_permission
    if current_user.present?
      roles = current_user.roles.pluck(:code).map &:to_sym  
      role_permissions = permissions.values_at(*roles).compact
      controllers = []
      role_permissions.each { |x| controllers << x.keys }
      if !controllers.flatten.blank? && controllers.flatten.include?(controller_path.to_sym)
        actions = []
        role_permissions.each { |x| actions << x[controller_path.to_sym] }
        not_authorized unless actions.flatten.include?(action_name.to_sym)
      else
        not_authorized
      end
    else
      not_authorized
    end
  end
  
end